# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/malkaviano/Fast/UnrealEngine-5.4.3-release/LocalBuilds/Engine/Linux
GAMEPROJECTFILE =/media/malkaviano/Fast/Unreal Projects/AGDemonstration/AGDemonstration.uproject

TARGETS = \
	AGDemonstration-Linux-DebugGame  \
	AGDemonstration \
	AGDemonstrationEditor-Linux-DebugGame  \
	AGDemonstrationEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend AGDemonstrationEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug AGDemonstrationEditor-Linux-Debug


AGDemonstration-Linux-DebugGame:
	 $(PROJECTBUILD) AGDemonstration Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AGDemonstration:
	 $(PROJECTBUILD) AGDemonstration Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

AGDemonstrationEditor-Linux-DebugGame:
	 $(PROJECTBUILD) AGDemonstrationEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AGDemonstrationEditor:
	 $(PROJECTBUILD) AGDemonstrationEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
